# Generated by Django 3.1.7 on 2021-03-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=256)),
                ('Hectare', models.CharField(max_length=256)),
                ('Shift', models.CharField(max_length=2)),
                ('Date', models.DateField(max_length=256)),
                ('Hectare_Squirrel_Number', models.IntegerField()),
                ('Age', models.CharField(max_length=256)),
                ('Primary_Fur_Color', models.CharField(max_length=256)),
                ('Highlight_Fur_Color', models.CharField(max_length=256)),
                ('Combination_of_Primary_and_Highlight_Color', models.CharField(max_length=256)),
                ('Color_notes', models.CharField(max_length=256)),
                ('Location', models.CharField(max_length=256)),
                ('Above_Ground_Sighter_Measurement', models.CharField(max_length=256)),
                ('Specific_Location', models.CharField(max_length=256)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(max_length=256)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
                ('Other_Interactions', models.CharField(max_length=256)),
                ('Lat_Long', models.CharField(max_length=256)),
            ],
        ),
    ]
